
physics_engine: "physx"
pipeline: "cpu"
# sim_device: "cuda:0"
# rl_device: "cuda:0"
sim_device: "cpu"
rl_device: "cpu"
graphics_device_id: 0
num_gpus: 1

test: False
resume: 0
logdir: "~"
cptdir: ""
headless: False

defaults:
  - task: FrankaPick
  - train: ${task}
  - hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
